# Generated by Django 5.0.1 on 2024-01-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teste", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("carga", models.CharField(max_length=14)),
                ("investimento", models.CharField(max_length=14)),
            ],
        ),
    ]
